name: Deploy

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
        run: |
          npm run build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: static-spa
          path: build

  deploy:
    name: Deploy pages
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: static-spa
          path: output/

      #- name: Add CNAME
      #  run: echo "${{ vars.DOCS_DOMAIN }}" > output/CNAME

      - name: Push to the Docs Repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: 'output'
          destination-github-username: 'MartenM'
          destination-repository-name: 'SurveyPlusWebView '
          user-email: surveyplus@martenm.nl
          target-branch: main
          target-directory: site
